### ISSUE TITLE
Python's “is” operator behaves unexpectedly with integers, floats...

### ISSUE THREAD

**Issue by ecarreras** [jaimegildesagredo/expects#34]
Please see: http://stackoverflow.com/questions/306313/pythons-is-operator-behaves-unexpectedly-with-integers

An example:

```python
a = 255
b = 255
a is b
True

a = 257
b = 257
a is b
False
```

Also you can try doing `id()` for integers <= 256 and every time is the same id for integer, but when numbers is greater than 256 the id is changing every time.

For floats every time is different

**Comment by ecarreras** [comment]
Using `equal` solves the problem but it doesn't compare the types, which solves my problem but I think sometimes you want to check the value and the type

```python
a = 257
expect(a).to(equal(257.0))  # True

expect(a).to(be(257))  # AssertionError: Expected 257 to be 257
```

**Comment by jaimegildesagredo** [comment]
Hi Eduard!

First of all, thank you for your time contributing to expects and sorry for my delay with the answer.

Based on your link I think the right way to test if two integers (or arbitrary objects) are equal, is using the `==` operator and not `is`, which compares identities. In expects `equal` is equivalent to `==` and `be` to `is` (I think this is not documented at all, so failure in my side :-1: ).

So if you want to compare if two integers are equal, you should use the `equal` matcher. `be` should be used only to compare if two variables point to the same object.

Finally I'm going to close the PR. I prefer to improve the documentation for these matchers and their behavior.

Thank you again for your work and let me know if you need anything else.
